### ISSUE TITLE
Missing required "BuildDefinition" and "ArtifactName" argument for "Import-Artifact" operation

### ISSUE THREAD

**Issue by arisliang** [Inedo/bmx-teamcity#27]
I've recently upgraded the bm and tc extension. When creating a import artifact from teamcity operation, it gives missing required arguments error

The version i'm using now:
-------------------
Buildmaster v5.5.3
TeamCity extension v5.4.2

Sample script:
-------------------
template Build_Import_Template
{
    Import-Artifact
    (
        Credentials: teamcity,
        Project: <Root project>,
        BuildConfiguration: 1,
        Artifact: 1
    );
}

Error:
-----------------
There were one or more errors processing your script:
[Error] Line 3: Missing required "BuildDefinition" argument for "Import-Artifact" operation.
[Error] Line 3: Missing required "ArtifactName" argument for "Import-Artifact" operation.

on the visual mode, it shows as VSO artifact, instead of TeamCity artifact
-------------
Import VSO Artifact
from using the last successful build of any build definition.

Update:
comparing the new scripts with old scripts that worked before, it seems pointing to TeamCity namespace that is missing in the new script. Is the namespace not generated correctly in the new version of extension?

**Comment by arisliang** [comment]
and on the visual mode, it shows as VSO artifact, instead of TeamCity artifact.
---------------
Import VSO Artifact
from using the last successful build of any build definition.

**Comment by jrasch** [comment]
I believe we answered this specific issue via support ticket a while ago and forgot to update here, but just to clarify for the public - this has already been resolved in a later version of BuildMaster. The issue was that the plan editor was ignoring the ScriptNamespace attribute's default setting (i.e. PreferUnqualified = false), so switching back and forth from text mode would remove the namespace. Since it had the same name as the operation in the TFS extension, it caused odd validation conflicts.
